spring.application.name=paypilot-backend

spring.datasource.url=jdbc:mysql://localhost:3306/paypilot
spring.datasource.username=root
spring.datasource.password=ENTER_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

gemini.api.key=${GEMINI_API_KEY}